#### Q1. If you have any, what are your choices for increasing the comparison between different figures on the same graph?

For increasing comparision, one can :
    
1. Change the colors ,i.e., a distinct color for each figure and attach labels to it to make more understandable.

2. Change the pattern of the figures. One can assign a unique pattern for each figure ,e.g., line, dotted , degree of bold,etc. Attach labels along with it for the same reason as above.


#### Q2. Can you explain the benefit of compound interest over a higher rate of interest that does not compound after reading this chapter?

Which chapter? Question isn't clear.

#### Q3. What is a histogram, exactly? Name a numpy method for creating such a graph.

Histogram is a graphical display of data using bars of different heights , where the heights may stand for frequency or the percentile value.

numpy.histogram() is a bulit-in numpy function for creating a histogram representation.

#### Q4. If necessary, how do you change the aspect ratios between the X and Y axes?

The aspect ratio can be changed by using figure(figsize=(10,8)) function inside the matplot.pyplot library which we scale down or up the graph.

#### 5. Summarize the differences in array multiplication between two arrays, as it is used in these three forms: dot product, outer product, and standard multiplication of two numpy arrays.

The standard multiplication multiplies two arrays placewise/positionwise.

The dot product does the vector multiplication of two matrices represented as arrays.

In outer product, every element of one array will be multiplied by every element of other array such that the number of columns in the output array will be equal to the number of elements in the second array.

Below are the examples of each.

In [5]:
import numpy as np

a1=np.array([[1,2,3],[4,5,6],[6,7,8]])
a2=np.array([[10,20,30],[40,50,60],[60,70,80]])

#standard
print("Standard: \n",a1*a2,"\n")

#dot
print("Dot: \n",np.dot(a1,a2),"\n")

#outer
print("Outer: \n",np.outer(a1,a2))


Standard: 
 [[ 10  40  90]
 [160 250 360]
 [360 490 640]] 

Dot: 
 [[ 270  330  390]
 [ 600  750  900]
 [ 820 1030 1240]] 

Outer: 
 [[ 10  20  30  40  50  60  60  70  80]
 [ 20  40  60  80 100 120 120 140 160]
 [ 30  60  90 120 150 180 180 210 240]
 [ 40  80 120 160 200 240 240 280 320]
 [ 50 100 150 200 250 300 300 350 400]
 [ 60 120 180 240 300 360 360 420 480]
 [ 60 120 180 240 300 360 360 420 480]
 [ 70 140 210 280 350 420 420 490 560]
 [ 80 160 240 320 400 480 480 560 640]]


#### Q6. Before you buy a home, which numpy function will you use to measure your monthly mortgage payment?

One needs to use: **np.pmt(rate, nper, pv)**

where, ate = The periodic interest rate

nper = The number of payment periods

pv = The total mortgage loan

#### Q7. Can numpy arrays store string data? If so, state at least one limitation that is imposed on this data.

Yes numpy arrays can store string data.The drawback is that the dtype of any such array is the maximum length of any string present in the array. so once assigned, it can only store a new string if it's length is not more than the maximum length at the time the string array was created.